---
- name: MySQL Health Check and Monitoring
  hosts: mysql_servers
  become: yes
  
  tasks:
    - name: Install MySQL Python connector
      ansible.builtin.pip:
        name: mysql-connector-python
        state: present

    - name: Check Database Space Utilization
      mysql_db:
        login_host: "{{ MYSQLHOST }}"
        login_port: "{{ MYSQLPORT }}"
        login_user: "{{ MYSQLUSER }}"
        login_password: "{{ MYSQLPASSWORD }}"
        db: "{{ MYSQLDATABASE }}"
        state: query
        query: |
          SELECT table_schema AS 'Database',
                 SUM(data_length + index_length) / 1024 / 1024 AS 'Size (MB)'
          FROM information_schema.tables
          GROUP BY table_schema;
      register: db_space

    - name: Display Database Space Utilization
      debug:
        msg: "{{ db_space.query_result }}"

    - name: Check Database Health (Uptime)
      mysql_db:
        login_host: "{{ MYSQLHOST }}"
        login_port: "{{ MYSQLPORT }}"
        login_user: "{{ MYSQLUSER }}"
        login_password: "{{ MYSQLPASSWORD }}"
        db: "{{ MYSQLDATABASE }}"
        state: query
        query: |
          SHOW STATUS LIKE 'Uptime';
      register: db_uptime

    - name: Display Database Uptime
      debug:
        msg: "Uptime: {{ db_uptime.query_result }}"

    - name: Check Threads Connected
      mysql_db:
        login_host: "{{ MYSQLHOST }}"
        login_port: "{{ MYSQLPORT }}"
        login_user: "{{ MYSQLUSER }}"
        login_password: "{{ MYSQLPASSWORD }}"
        db: "{{ MYSQLDATABASE }}"
        state: query
        query: |
          SHOW STATUS LIKE 'Threads_connected';
      register: threads_connected

    - name: Display Threads Connected
      debug:
        msg: "Threads connected: {{ threads_connected.query_result }}"

    - name: Check for Deadlocks
      mysql_db:
        login_host: "{{ MYSQLHOST }}"
        login_port: "{{ MYSQLPORT }}"
        login_user: "{{ MYSQLUSER }}"
        login_password: "{{ MYSQLPASSWORD }}"
        db: "{{ MYSQLDATABASE }}"
        state: query
        query: |
          SHOW ENGINE INNODB STATUS;
      register: deadlock_status

    - name: Check if Deadlocks are present
      debug:
        msg: |
          {% if 'LATEST DETECTED DEADLOCK' in deadlock_status.query_result %}
            Deadlock detected:
            {{ deadlock_status.query_result }}
          {% else %}
            No deadlocks detected.
          {% endif %}

    - name: Check Job Activities (Running Queries)
      mysql_db:
        login_host: "{{ MYSQLHOST }}"
        login_port: "{{ MYSQLPORT }}"
        login_user: "{{ MYSQLUSER }}"
        login_password: "{{ MYSQLPASSWORD }}"
        db: "{{ MYSQLDATABASE }}"
        state: query
        query: |
          SHOW PROCESSLIST;
      register: job_activities

    - name: Display Current Running Queries
      debug:
        msg: |
          {% for job in job_activities.query_result %}
            ID: {{ job.id }}, User: {{ job.user }}, Command: {{ job.command }},
            Time: {{ job.time }}, Info: {{ job.info }}
          {% endfor %}
