---
- name: Connect to MySQL server on Linux
  hosts: localhost
  become: yes

  tasks:
    - name: Ensure MySQL is installed
      package:
        name: mysql-client
        state: present

    - name: Test MySQL connection
      community.mysql.mysql_db:
        name: information_schema
        state: import
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        # You can also use `ssl` options here if needed

    - name: List databases
      community.mysql.mysql_db:
        name: "{{ item }}"
        state: list
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
      loop:
        - information_schema
        - performance_schema
        - mysql
