---
- name: MySQL Health Check and Monitoring
  hosts: localhost
  become: yes
  vars:
    mysql_user: "mysql_user"
    mysql_password: "mysql_password"
    mysql_host: "mysql_host"
    mysql_port: "mysql_port"

  tasks:
    - name: Check MySQL Database Space Usage
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SELECT table_schema AS db_name, SUM(data_length + index_length) / 1024 / 1024 AS db_size_mb FROM information_schema.tables GROUP BY table_schema;"
      register: db_space_usage

    - name: Display Database Space Usage
      debug:
        msg: "{{ db_space_usage.query_result }}"

    - name: Check MySQL Database Utilization
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW STATUS LIKE 'Innodb_buffer_pool%';"
      register: db_utilization

    - name: Display Database Utilization
      debug:
        msg: "{{ db_utilization.query_result }}"

    - name: Check MySQL Health Status
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW ENGINE INNODB STATUS;"
      register: db_health_status

    - name: Display MySQL Health Status
      debug:
        msg: "{{ db_health_status.query_result }}"

    - name: Check for MySQL Deadlocks
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW ENGINE INNODB STATUS;"
      register: deadlocks

    - name: Display Deadlock Information
      debug:
        msg: "{{ deadlocks.query_result | selectattr('Msg_text', 'search', 'deadlock') | list }}"

    - name: Check for Active Jobs in MySQL
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW PROCESSLIST;"
      register: active_jobs

    - name: Display Active Jobs
      debug:
        msg: "{{ active_jobs.query_result }}"

