---
- name: Perform MySQL Server Health and Resource Checks
  hosts: localhost
  gather_facts: yes  # Automatically gather system facts (CPU, memory, etc.)
  become: yes
  vars:
    mysql_user: "{{mysql_user}}"
    mysql_password: "{{mysql_password}}"
    mysql_host: "{{mysql_host}}"
    mysql_port: {{mysql_port}}"
    mysql_db: "{{mysql_db}}"

  tasks:
    - name: Check disk space on server
      shell: df -h /
      register: disk_space
      ignore_errors: true

    - name: Display disk space
      debug:
        msg: "{{ disk_space.stdout }}"

    - name: Check MySQL database utilization
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SELECT table_schema AS DB_NAME, SUM(data_length + index_length) / 1024 / 1024 AS DB_SIZE_MB FROM information_schema.tables GROUP BY table_schema;"
      register: db_utilization
      ignore_errors: true

    - name: Display database utilization
      debug:
        msg: "{{ db_utilization.query_result }}"

    - name: Check MySQL health (Uptime)
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW STATUS LIKE 'Uptime';"
      register: db_health
      ignore_errors: true

    - name: Display MySQL health (Uptime)
      debug:
        msg: "{{ db_health.query_result }}"

    - name: Check for MySQL deadlocks
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW ENGINE INNODB STATUS;"
      register: deadlocks
      ignore_errors: true

    - name: Display deadlock information
      debug:
        msg: "{{ deadlocks.query_result | selectattr('message', 'search', 'DEADLOCK') | list }}"

    - name: Check MySQL process list (jobs/queries)
      mysql_query:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW PROCESSLIST;"
      register: mysql_jobs
      ignore_errors: true

    - name: Display current MySQL jobs
      debug:
        msg: "{{ mysql_jobs.query_result }}"

    - name: Monitor CPU and memory usage
      debug:
        msg:
          - "CPU Usage: {{ ansible_facts['processor_cores'] }} cores"
          - "CPU Load: {{ ansible_facts['processor'] }}"
          - "Memory Usage: {{ ansible_facts['memtotal_mb'] }} MB Total"
          - "Memory Used: {{ ansible_facts['memused_mb'] }} MB"
