- name: MySQL Database Monitoring
  hosts: localhost
  gather_facts: false
  vars:
    mysql_host: "127.0.0.1"
    mysql_user: "mysqlAutomation"
    mysql_password: "mysqlAutomation"
    mysql_database: "MYSQLSV"
    mysql_port: 3306
 
  tasks:
    - name: Check MySQL Connection
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
        query: "SELECT VERSION();"
      register: mysql_version
 
    - name: Show MySQL Version
      debug:
        msg: "Connected to MySQL Server - Version: {{ mysql_version.query_result[0]['VERSION()'] }}"
 
    - name: Check Database Space Utilization
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
        query: |
          SELECT table_schema AS Database, 
                 SUM(data_length + index_length) / 1024 / 1024 AS Size_MB
          FROM information_schema.tables
          GROUP BY table_schema;
      register: db_space
 
    - name: Display Database Space Utilization
      debug:
        msg: "{{ db_space.query_result }}"
 
    - name: Check MySQL Uptime and Connections
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
        query: 
          - "SHOW STATUS LIKE 'Uptime';"
          - "SHOW STATUS LIKE 'Threads_connected';"
      register: mysql_health
 
    - name: Display Database Health
      debug:
        msg: "Uptime: {{ mysql_health.query_result[0]['Value'] }} seconds, Threads Connected: {{ mysql_health.query_result[1]['Value'] }}"
 
    - name: Check for Deadlocks in MySQL
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW ENGINE INNODB STATUS;"
      register: deadlock_status
 
    - name: Display Deadlock Information
      debug:
        msg: "Deadlock Info: {{ deadlock_status.query_result | regex_search('LATEST DETECTED DEADLOCK') | default('No deadlocks detected') }}"
 
    - name: Check Running Queries (Job Activities)
      community.mysql.mysql_query:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_port: "{{ mysql_port }}"
        query: "SHOW PROCESSLIST;"
      register: job_activities
 
    - name: Display Running Queries
      debug:
        msg: "{{ job_activities.query_result }}"
