---
- name: Check MySQL Database Space
  hosts: my_servers
  become: yes  # If needed to use sudo privileges
  tasks:
    - name: Ensure MySQL client is installed
      package:
        name: mysql-client
        state: present

    - name: Get database size from MySQL
      mysql_db:
        name: MYSQLSV
        state: query
        login_user: root  # Adjust the login user
        login_password: "{{ mysql_root_password }}"  # Use an Ansible variable for security
        query: "SELECT table_schema AS 'Database', 
                        SUM(data_length + index_length) / 1024 / 1024 AS 'Size (MB)' 
                 FROM information_schema.tables 
                 GROUP BY table_schema;"
      register: db_space

    - name: Show database sizes
      debug:
        msg: "{{ db_space.query_result }}"
